services:
  - type: web
    name: BLOGApp
    env: python
    rootDir: blogsuggestion
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn MenuSuggestion.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
