"""
Django settings for project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""
import os
import warnings
from pathlib import Path
from django.contrib import messages
from dotenv import load_dotenv

# .envファイルを最優先で読み込む（波線対策・環境変数ロード）
load_dotenv()

# 古いgoogle-generativeaiの非推奨警告を非表示にする
warnings.filterwarnings("ignore", category=FutureWarning, module="google.generativeai")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u_i22yuz$zq#xkq5*n1$1-ftc5wm7#9-$9kz6elhu&7z)1tjt1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['nnjrg248.pythonanywhere.com', '127.0.0.1', 'localhost']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Suggestion',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_summernote', 
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# --- allauthの細かい挙動設定 ---
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_MESSAGES = False
ACCOUNT_SITE_NAME = "nnjrg842ブログサポート"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[nnjrg842ブログサポート] "

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'MenuSuggestion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MenuSuggestion.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Summernote RichText Editor Configuration
SUMMERNOTE_CONFIG = {
    'iframe': False,
    'summernote': {
        'lineHeights': ['0.5', '1.0', '1.5'],
        'disableResizeEditor': False,
        'styleTags': ['p', 'br'],
    },
    'css': ('/static/summernote/custom.css',),
    'lang': 'ja-JP',
}

# Internationalization
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# Static & Media files (Local)
STATIC_URL = '/static/' 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login / Logout Redirect URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'post_list'
ACCOUNT_LOGOUT_REDIRECT_URL = 'post_list'

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Email Settings (Gmail SMTP)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587#465#587

EMAIL_USE_TLS =True#False #True
EMAIL_USE_SSL =False #True #False

EMAIL_HOST_USER = 'nnjrg842@gmail.com'
#DEFAULT_FROM_EMAIL = f"{ACCOUNT_SITE_NAME} <{EMAIL_HOST_USER}>"

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
#########################リセンドのメール設定なのでgmail設定に戻すこともあるのでgmailの設定は残しとく
import os
# 1. allauthのアカウント認証メール設定（既存の設定があれば確認してください）
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # 登録時にメール認証を必須にする場合
# 2. メール送信バックエンドを Resend に指定
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
}
#DEFAULT_FROM_EMAIL = "onboarding@resend.dev"
#ACCOUNT_EMAIL_FROM_EMAIL = "onboarding@resend.dev"
DEFAULT_FROM_EMAIL = "noreply@1q1q.xyz"
ACCOUNT_EMAIL_FROM_EMAIL = "noreply@1q1q.xyz"
# --- django-allauth の基本設定 ---
# ログインや認証の方法を指定します
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[BLIOGapp] " # メールの件名の頭に付く文字



# Cloudflare R2 (S3互換ストレージ) 設定
AWS_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = f'https://{os.getenv("R2_ACCOUNT_ID")}.r2.cloudflarestorage.com'

# 外部公開用URLのベース設定
AWS_S3_CUSTOM_DOMAIN = os.getenv("R2_CUSTOM_DOMAIN", "").replace("https://", "")
AWS_S3_URL_PROTOCOL = 'https'
AWS_QUERYSTRING_AUTH = False  # ブログ閲覧用にURL認証期限を無効化

# R2容量制限（無料枠超過防止用）
MAX_FILE_SIZE = 2 * 1024 * 1024  # 1ファイル最大 2MB
MAX_TOTAL_SIZE = 9.5 * 1024 * 1024 * 1024  # 全体最大 9.5GB

SUMMERNOTE_CONFIG = {
    'iframe': False,
}
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Email Settings (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # ←ここの「#」を消して有効化！
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'nnjrg842@gmail.com'  # ※宛先のメールアドレス
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# --- django-allauth の基本設定 ---
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# 送信元メールアドレスの設定（Gmailに合わせる）
DEFAULT_FROM_EMAIL = f"{ACCOUNT_SITE_NAME} <{EMAIL_HOST_USER}>"

# ⚠️ 注意：以下の Resend の設定は「#」をつけてすべて無効化（コメントアウト）します！
# EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
# ANYMAIL = {
#     "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
# }

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[BLIOGapp] "