# Generated by Django 6.0.2 on 2026-06-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion', '0003_post_likes_post_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views_count',
        ),
    ]
