# Generated by Django 6.0.2 on 2026-06-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion', '0005_delete_post_memo_likes_memo_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='total_likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
